import { Resvg } from '@resvg/resvg-js';
import type { WeeklyData } from '../types/github.types.js';
import type { NarratorOutput } from '../types/blog.types.js';

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function fmt(n: number): string {
  return n.toLocaleString('en-US');
}

/** Build a deterministic 1200x630 stats card SVG from the week's data. Pure. */
export function buildStatsCardSvg(data: WeeklyData, blog: NarratorOutput['blog']): string {
  const topLangs = Object.entries(data.languages)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([l]) => l)
    .join(' · ');
  const headlineText = blog.headline.slice(0, 80);
  const headline = escapeXml(headlineText);
  const headlineSize = headlineText.length > 52 ? 34 : headlineText.length > 40 ? 40 : 46;
  const week = escapeXml(`${data.weekStart} → ${data.weekEnd}`);
  const stats: Array<[string, string]> = [
    [fmt(data.totalCommits), 'commits'],
    [fmt(data.totalPRs), 'PRs'],
    [fmt(data.totalReviews), 'reviews'],
    [`+${fmt(data.totalAdditions)}`, 'added'],
    [`-${fmt(data.totalDeletions)}`, 'removed'],
    [String(data.repos.length), 'repos'],
  ];
  const cells = stats
    .map(([value, label], i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 90 + col * 360;
      const y = 320 + row * 150;
      return `
      <text x="${x}" y="${y}" fill="#818cf8" font-size="64" font-weight="700" font-family="sans-serif">${escapeXml(value)}</text>
      <text x="${x}" y="${y + 38}" fill="#a1a1aa" font-size="26" font-family="sans-serif">${escapeXml(label)}</text>`;
    })
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#0f0f0f"/>
  <rect x="0" y="0" width="1200" height="8" fill="#6366f1"/>
  <text x="90" y="120" fill="#e5e5e5" font-size="${headlineSize}" font-weight="700" font-family="sans-serif">${headline}</text>
  <text x="90" y="170" fill="#71717a" font-size="28" font-family="sans-serif">${week} · ${escapeXml(topLangs)}</text>
  ${cells}
  <text x="90" y="590" fill="#52525b" font-size="24" font-family="sans-serif">Generated by DevNotion</text>
</svg>`;
}

/** Rasterize an SVG string to PNG bytes. */
export function svgToPng(svg: string): Uint8Array {
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: 1200 },
    font: { loadSystemFonts: true, defaultFontFamily: 'sans-serif' },
  });
  return resvg.render().asPng();
}
