import { Resvg } from '@resvg/resvg-js';
import type { WeeklyData } from '../types/github.types.js';
import type { NarratorOutput } from '../types/blog.types.js';

// resvg-js matches fonts by concrete family name — it does NOT resolve the CSS
// generic "sans-serif" (it silently falls back to a serif). Use a concrete
// stack: Liberation Sans on Linux/CI, Arial/Helvetica on macOS, generic last.
const FONT = "'Liberation Sans', Arial, 'Helvetica Neue', sans-serif";

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function fmt(n: number): string {
  return n.toLocaleString('en-US');
}

/** Greedily wrap text into at most `maxLines` lines of ~`maxChars`; ellipsize overflow. */
function wrapTitle(text: string, maxChars: number, maxLines: number): string[] {
  const lines: string[] = [];
  let cur = '';
  for (const word of text.split(/\s+/)) {
    if (cur && (cur + ' ' + word).length > maxChars) {
      lines.push(cur);
      cur = word;
    } else {
      cur = cur ? cur + ' ' + word : word;
    }
  }
  if (cur) lines.push(cur);
  if (lines.length <= maxLines) return lines;
  const kept = lines.slice(0, maxLines);
  kept[maxLines - 1] = kept[maxLines - 1]!.slice(0, maxChars - 1).trimEnd() + '…';
  return kept;
}

/** Build a deterministic 1200x630 stats card SVG from the week's data. Pure. */
export function buildStatsCardSvg(data: WeeklyData, blog: NarratorOutput['blog']): string {
  const topLangs = Object.entries(data.languages)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([l]) => l)
    .join(' · ');
  // The card shows the clean title — strip the "Dev log #n" prefix the article keeps.
  const rawTitle = blog.headline.replace(/^Dev log #\d+\s+/i, '').slice(0, 110);
  const titleSize = rawTitle.length > 46 ? 42 : 48;
  const maxChars = titleSize === 42 ? 44 : 38;
  const titleLines = wrapTitle(rawTitle, maxChars, 2);
  const lineGap = titleSize + 12;
  const title = titleLines
    .map((line, i) => `<text x="90" y="${118 + i * lineGap}" fill="#e5e5e5" font-size="${titleSize}" font-weight="700" font-family="${FONT}">${escapeXml(line)}</text>`)
    .join('\n  ');
  const subY = 118 + (titleLines.length - 1) * lineGap + 44;
  const subtitle = topLangs
    ? `<text x="90" y="${subY}" fill="#71717a" font-size="28" font-family="${FONT}">${escapeXml(topLangs)}</text>`
    : '';

  const stats: Array<[string, string]> = [
    [fmt(data.totalCommits), 'commits'],
    [fmt(data.totalPRs), 'PRs'],
    [fmt(data.totalReviews), 'reviews'],
    [`+${fmt(data.totalAdditions)}`, 'added'],
    [`-${fmt(data.totalDeletions)}`, 'removed'],
    [String(data.repos.length), 'repos'],
  ];
  const cells = stats
    .map(([value, label], i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 90 + col * 360;
      const y = 330 + row * 150;
      return `
      <text x="${x}" y="${y}" fill="#818cf8" font-size="64" font-weight="700" font-family="${FONT}">${escapeXml(value)}</text>
      <text x="${x}" y="${y + 38}" fill="#a1a1aa" font-size="26" font-family="${FONT}">${escapeXml(label)}</text>`;
    })
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#0f0f0f"/>
  <rect x="0" y="0" width="1200" height="8" fill="#6366f1"/>
  ${title}
  ${subtitle}
  ${cells}
  <text x="90" y="590" fill="#52525b" font-size="24" font-family="${FONT}">Generated by DevNotion</text>
</svg>`;
}

/** Rasterize an SVG string to PNG bytes. */
export function svgToPng(svg: string): Uint8Array {
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: 1200 },
    font: { loadSystemFonts: true, defaultFontFamily: 'Liberation Sans' },
  });
  return resvg.render().asPng();
}
