import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

export interface BlogLogEntry {
  weekStart: string;
  weekEnd: string;
  headline: string;
  repoCount: number;
  totalCommits: number;
  totalPRs: number;
  totalIssues: number;
  totalReviews: number;
  totalAdditions: number;
  totalDeletions: number;
  topLanguages: string[];
  notionPageUrl?: string;
  devtoUrl?: string;
}

const LOG_PATH = resolve(process.cwd(), 'blog/README.md');

const HEADER = `# GitPulse — Blog Log

Automated weekly dev blog posts generated by [GitPulse](https://github.com/yashksaini-coder/GitPulse).
Published to **Notion** + **DEV.to** every Sunday via CI.

---

| Week | Headline | Repos | Commits | PRs | Issues | Reviews | Lines Changed | Languages | Notion | DEV.to |
|------|----------|-------|---------|-----|--------|---------|---------------|-----------|--------|--------|`;

function formatRow(e: BlogLogEntry): string {
  const lines = `+${e.totalAdditions.toLocaleString()}/-${e.totalDeletions.toLocaleString()}`;
  const langs = e.topLanguages.join(', ') || '—';
  const notion = e.notionPageUrl ? `[View](${e.notionPageUrl})` : '—';
  const devto = e.devtoUrl ? `[Draft](${e.devtoUrl})` : '—';
  const headline = e.headline.length > 50 ? e.headline.slice(0, 47) + '...' : e.headline;

  return `| ${e.weekStart} | ${headline} | ${e.repoCount} | ${e.totalCommits} | ${e.totalPRs} | ${e.totalIssues} | ${e.totalReviews} | ${lines} | ${langs} | ${notion} | ${devto} |`;
}

export function updateBlogLog(entry: BlogLogEntry): void {
  mkdirSync(resolve(process.cwd(), 'blog'), { recursive: true });

  let content: string;
  try {
    content = readFileSync(LOG_PATH, 'utf-8');
  } catch {
    content = HEADER;
  }

  let lines = content.split('\n');

  // Find the table header row; reset to HEADER if missing
  let headerIdx = lines.findIndex((l) => l.startsWith('| Week'));
  if (headerIdx === -1) {
    lines = HEADER.split('\n');
    headerIdx = lines.findIndex((l) => l.startsWith('| Week'));
  }

  // Check if this week already exists (idempotent)
  const existingIdx = lines.findIndex((l) => l.startsWith(`| ${entry.weekStart} `));
  const newRow = formatRow(entry);

  if (existingIdx !== -1) {
    lines[existingIdx] = newRow;
  } else {
    // Insert after separator row (headerIdx + 1 is the |---| row)
    lines.splice(headerIdx + 2, 0, newRow);
  }

  writeFileSync(LOG_PATH, lines.join('\n'), 'utf-8');
  console.log(`Blog log updated: ${LOG_PATH}`);
}
